/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIVersion;

/**
 *
 * @author Mark
 */
public class StackConvert extends javax.swing.JFrame {

    /**
     * Creates new form StackConvert
     */
    public StackConvert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CONVERT_BUTTON = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        StackOf64 = new javax.swing.JTextField();
        Remain64 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        StackOf16 = new javax.swing.JTextField();
        Remain16 = new javax.swing.JTextField();
        NumberOfItems = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stack Converter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Number of Items:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("In a stack of 16:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Remaining Items: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, 20));

        CONVERT_BUTTON.setBackground(new java.awt.Color(204, 102, 0));
        CONVERT_BUTTON.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        CONVERT_BUTTON.setForeground(new java.awt.Color(255, 255, 255));
        CONVERT_BUTTON.setText("Convert");
        CONVERT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONVERT_BUTTONActionPerformed(evt);
            }
        });
        jPanel1.add(CONVERT_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("In a stack of 64:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Remaining Items: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jPanel2.setBackground(new java.awt.Color(38, 38, 38));

        StackOf64.setEditable(false);
        StackOf64.setBackground(new java.awt.Color(255, 255, 255));
        StackOf64.setForeground(new java.awt.Color(0, 0, 0));
        StackOf64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StackOf64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StackOf64ActionPerformed(evt);
            }
        });

        Remain64.setEditable(false);
        Remain64.setBackground(new java.awt.Color(255, 255, 255));
        Remain64.setForeground(new java.awt.Color(0, 0, 0));
        Remain64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Remain64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remain64ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(StackOf64, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Remain64, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StackOf64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Remain64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 80));

        jPanel3.setBackground(new java.awt.Color(38, 38, 38));

        StackOf16.setEditable(false);
        StackOf16.setBackground(new java.awt.Color(255, 255, 255));
        StackOf16.setForeground(new java.awt.Color(0, 0, 0));
        StackOf16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StackOf16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StackOf16ActionPerformed(evt);
            }
        });

        Remain16.setEditable(false);
        Remain16.setBackground(new java.awt.Color(255, 255, 255));
        Remain16.setForeground(new java.awt.Color(0, 0, 0));
        Remain16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Remain16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remain16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StackOf16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Remain16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StackOf16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Remain16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        NumberOfItems.setBackground(new java.awt.Color(255, 255, 255));
        NumberOfItems.setForeground(new java.awt.Color(0, 0, 0));
        NumberOfItems.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumberOfItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfItemsActionPerformed(evt);
            }
        });
        jPanel1.add(NumberOfItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StackOf64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StackOf64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StackOf64ActionPerformed

    private void CONVERT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONVERT_BUTTONActionPerformed
        // TODO add your handling code here:
        String n;
        int item;
        
        n = NumberOfItems.getText();
        
        item=Integer.parseInt(n);
        
        StackOf64.setText(""+item/64);
        Remain64.setText(""+item%64);
        StackOf16.setText(""+item/16);
        Remain16.setText(""+item%16);
    }//GEN-LAST:event_CONVERT_BUTTONActionPerformed

    private void NumberOfItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberOfItemsActionPerformed

    private void StackOf16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StackOf16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StackOf16ActionPerformed

    private void Remain64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remain64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Remain64ActionPerformed

    private void Remain16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remain16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Remain16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StackConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StackConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StackConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StackConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StackConvert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONVERT_BUTTON;
    private javax.swing.JTextField NumberOfItems;
    private javax.swing.JTextField Remain16;
    private javax.swing.JTextField Remain64;
    private javax.swing.JTextField StackOf16;
    private javax.swing.JTextField StackOf64;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
